// <auto-generated />
using System;
using Aromo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aromo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aromo.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Aromo.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Arabica"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aladin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Amouage"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Armaf"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Azzaro"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bvlgari"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dessert Rose"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Habibi Air"
                        });
                });

            modelBuilder.Entity("Aromo.Models.Catalogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Catalogues");
                });

            modelBuilder.Entity("Aromo.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Мъжки"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Дамски"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Унисекс"
                        });
                });

            modelBuilder.Entity("Aromo.Models.Perfume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("GenderId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("Name", "BrandId", "Volume")
                        .IsUnique();

                    b.ToTable("Perfumes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            GenderId = 3,
                            Name = "Mystic Oud",
                            Original = "Versace Inspiration",
                            Price = 199.99m,
                            SeasonId = 4,
                            Volume = 100
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 7,
                            GenderId = 2,
                            Name = "Desert Rose",
                            Original = "Dior Salage",
                            Price = 149.99m,
                            SeasonId = 2,
                            Volume = 50
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 4,
                            GenderId = 1,
                            Name = "Ocean Breeze",
                            Original = "Davidoff Cool Water",
                            Price = 89.99m,
                            SeasonId = 14,
                            Volume = 75
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 3,
                            GenderId = 3,
                            Name = "Golden Sandal",
                            Original = "Guerlain Santal Royal",
                            Price = 249.99m,
                            SeasonId = 24,
                            Volume = 100
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 5,
                            GenderId = 1,
                            Name = "Amber Night",
                            Original = "Yves Saint Laurent La Nuit de L'Homme",
                            Price = 129.99m,
                            SeasonId = 13,
                            Volume = 100
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            GenderId = 2,
                            Name = "Velvet Jasmine",
                            Original = "Chanel Chance Eau Tendre",
                            Price = 109.99m,
                            SeasonId = 1234,
                            Volume = 50
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 6,
                            GenderId = 3,
                            Name = "Citrus Bloom",
                            Original = "Dolce & Gabbana Light Blue",
                            Price = 99.99m,
                            SeasonId = 12,
                            Volume = 75
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 8,
                            GenderId = 2,
                            Name = "Midnight Vanilla",
                            Original = "Tom Ford Black Orchid",
                            Price = 139.99m,
                            SeasonId = 4,
                            Volume = 100
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            GenderId = 1,
                            Name = "Forest Whisper",
                            Original = "Hermes Terre d'Hermes",
                            Price = 179.99m,
                            SeasonId = 13,
                            Volume = 100
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 6,
                            GenderId = 3,
                            Name = "White Musk",
                            Original = "Narciso Rodriguez For Her",
                            Price = 119.99m,
                            SeasonId = 134,
                            Volume = 50
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 1,
                            GenderId = 1,
                            Name = "Oriental Spice",
                            Original = "Spicebomb by Viktor & Rolf",
                            Price = 189.99m,
                            SeasonId = 124,
                            Volume = 100
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 7,
                            GenderId = 2,
                            Name = "Rosewood Elegance",
                            Original = "Chloé Nomade",
                            Price = 159.99m,
                            SeasonId = 23,
                            Volume = 75
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 4,
                            GenderId = 1,
                            Name = "Aqua Mint",
                            Original = "Acqua di Gio by Giorgio Armani",
                            Price = 79.99m,
                            SeasonId = 24,
                            Volume = 50
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 3,
                            GenderId = 3,
                            Name = "Royal Incense",
                            Original = "Amouage Interlude",
                            Price = 269.99m,
                            SeasonId = 4,
                            Volume = 100
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 6,
                            GenderId = 2,
                            Name = "Sunny Neroli",
                            Original = "Neroli Portofino by Tom Ford",
                            Price = 99.99m,
                            SeasonId = 2,
                            Volume = 75
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 5,
                            GenderId = 1,
                            Name = "Dark Leather",
                            Original = "John Varvatos Dark Rebel",
                            Price = 149.99m,
                            SeasonId = 1,
                            Volume = 100
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 2,
                            GenderId = 3,
                            Name = "Soft Lavender",
                            Original = "Lavender Eau by Jo Malone",
                            Price = 89.99m,
                            SeasonId = 14,
                            Volume = 50
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 8,
                            GenderId = 3,
                            Name = "Habibi Gold",
                            Original = "Habibi Classic",
                            Price = 219.99m,
                            SeasonId = 13,
                            Volume = 100
                        });
                });

            modelBuilder.Entity("Aromo.Models.Scent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Scents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Мед"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Роза"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ванилия"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Канела"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Кедрово дърво"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Морски"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Портокал"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Жасмин"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ориенталски"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Бергамот"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Лавандула"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Сандалово дърво"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Мускус"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Розмарин"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Боровинка"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Мента"
                        });
                });

            modelBuilder.Entity("Aromo.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Пролет"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Лято"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Есен"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Зима"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Пролет/Лято"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Пролет/Есен"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Пролет/Зима"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Лято/Есен"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Лято/Зима"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Есен/Зима"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Пролет/Лято/Есен"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Пролет/Лято/Зима"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Пролет/Есен/Зима"
                        },
                        new
                        {
                            Id = 1234,
                            Name = "Целогодишен"
                        });
                });

            modelBuilder.Entity("CataloguePerfume", b =>
                {
                    b.Property<int>("CataloguesId")
                        .HasColumnType("int");

                    b.Property<int>("PerfumesId")
                        .HasColumnType("int");

                    b.HasKey("CataloguesId", "PerfumesId");

                    b.HasIndex("PerfumesId");

                    b.ToTable("CataloguePerfume");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PerfumeBaseScents", b =>
                {
                    b.Property<int>("PerfumeId")
                        .HasColumnType("int");

                    b.Property<int>("ScentId")
                        .HasColumnType("int");

                    b.HasKey("PerfumeId", "ScentId");

                    b.HasIndex("ScentId");

                    b.ToTable("PerfumeBaseScents");

                    b.HasData(
                        new
                        {
                            PerfumeId = 1,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 1,
                            ScentId = 13
                        },
                        new
                        {
                            PerfumeId = 1,
                            ScentId = 5
                        },
                        new
                        {
                            PerfumeId = 1,
                            ScentId = 1
                        },
                        new
                        {
                            PerfumeId = 2,
                            ScentId = 13
                        },
                        new
                        {
                            PerfumeId = 2,
                            ScentId = 3
                        },
                        new
                        {
                            PerfumeId = 2,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 3,
                            ScentId = 5
                        },
                        new
                        {
                            PerfumeId = 3,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 3,
                            ScentId = 13
                        },
                        new
                        {
                            PerfumeId = 4,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 4,
                            ScentId = 1
                        },
                        new
                        {
                            PerfumeId = 4,
                            ScentId = 13
                        },
                        new
                        {
                            PerfumeId = 4,
                            ScentId = 5
                        },
                        new
                        {
                            PerfumeId = 5,
                            ScentId = 13
                        },
                        new
                        {
                            PerfumeId = 5,
                            ScentId = 1
                        },
                        new
                        {
                            PerfumeId = 5,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 6,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 6,
                            ScentId = 5
                        },
                        new
                        {
                            PerfumeId = 6,
                            ScentId = 13
                        },
                        new
                        {
                            PerfumeId = 7,
                            ScentId = 1
                        },
                        new
                        {
                            PerfumeId = 7,
                            ScentId = 13
                        },
                        new
                        {
                            PerfumeId = 7,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 8,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 8,
                            ScentId = 5
                        },
                        new
                        {
                            PerfumeId = 8,
                            ScentId = 13
                        },
                        new
                        {
                            PerfumeId = 9,
                            ScentId = 5
                        },
                        new
                        {
                            PerfumeId = 9,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 9,
                            ScentId = 1
                        },
                        new
                        {
                            PerfumeId = 10,
                            ScentId = 13
                        },
                        new
                        {
                            PerfumeId = 10,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 10,
                            ScentId = 5
                        },
                        new
                        {
                            PerfumeId = 11,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 11,
                            ScentId = 13
                        },
                        new
                        {
                            PerfumeId = 11,
                            ScentId = 1
                        },
                        new
                        {
                            PerfumeId = 12,
                            ScentId = 1
                        },
                        new
                        {
                            PerfumeId = 12,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 12,
                            ScentId = 5
                        },
                        new
                        {
                            PerfumeId = 13,
                            ScentId = 5
                        },
                        new
                        {
                            PerfumeId = 13,
                            ScentId = 13
                        },
                        new
                        {
                            PerfumeId = 13,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 14,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 14,
                            ScentId = 1
                        },
                        new
                        {
                            PerfumeId = 14,
                            ScentId = 5
                        },
                        new
                        {
                            PerfumeId = 15,
                            ScentId = 13
                        },
                        new
                        {
                            PerfumeId = 15,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 15,
                            ScentId = 5
                        },
                        new
                        {
                            PerfumeId = 15,
                            ScentId = 1
                        },
                        new
                        {
                            PerfumeId = 16,
                            ScentId = 5
                        },
                        new
                        {
                            PerfumeId = 16,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 16,
                            ScentId = 13
                        },
                        new
                        {
                            PerfumeId = 17,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 17,
                            ScentId = 1
                        },
                        new
                        {
                            PerfumeId = 17,
                            ScentId = 5
                        },
                        new
                        {
                            PerfumeId = 18,
                            ScentId = 1
                        },
                        new
                        {
                            PerfumeId = 18,
                            ScentId = 12
                        },
                        new
                        {
                            PerfumeId = 18,
                            ScentId = 13
                        });
                });

            modelBuilder.Entity("PerfumeHeartScents", b =>
                {
                    b.Property<int>("PerfumeId")
                        .HasColumnType("int");

                    b.Property<int>("ScentId")
                        .HasColumnType("int");

                    b.HasKey("PerfumeId", "ScentId");

                    b.HasIndex("ScentId");

                    b.ToTable("PerfumeHeartScents");

                    b.HasData(
                        new
                        {
                            PerfumeId = 1,
                            ScentId = 9
                        },
                        new
                        {
                            PerfumeId = 1,
                            ScentId = 4
                        },
                        new
                        {
                            PerfumeId = 1,
                            ScentId = 8
                        },
                        new
                        {
                            PerfumeId = 2,
                            ScentId = 8
                        },
                        new
                        {
                            PerfumeId = 2,
                            ScentId = 3
                        },
                        new
                        {
                            PerfumeId = 2,
                            ScentId = 15
                        },
                        new
                        {
                            PerfumeId = 3,
                            ScentId = 11
                        },
                        new
                        {
                            PerfumeId = 3,
                            ScentId = 4
                        },
                        new
                        {
                            PerfumeId = 4,
                            ScentId = 2
                        },
                        new
                        {
                            PerfumeId = 4,
                            ScentId = 9
                        },
                        new
                        {
                            PerfumeId = 4,
                            ScentId = 3
                        },
                        new
                        {
                            PerfumeId = 5,
                            ScentId = 8
                        },
                        new
                        {
                            PerfumeId = 5,
                            ScentId = 15
                        },
                        new
                        {
                            PerfumeId = 6,
                            ScentId = 3
                        },
                        new
                        {
                            PerfumeId = 6,
                            ScentId = 4
                        },
                        new
                        {
                            PerfumeId = 6,
                            ScentId = 9
                        },
                        new
                        {
                            PerfumeId = 7,
                            ScentId = 2
                        },
                        new
                        {
                            PerfumeId = 7,
                            ScentId = 8
                        },
                        new
                        {
                            PerfumeId = 8,
                            ScentId = 9
                        },
                        new
                        {
                            PerfumeId = 8,
                            ScentId = 8
                        },
                        new
                        {
                            PerfumeId = 8,
                            ScentId = 15
                        },
                        new
                        {
                            PerfumeId = 9,
                            ScentId = 15
                        },
                        new
                        {
                            PerfumeId = 9,
                            ScentId = 3
                        },
                        new
                        {
                            PerfumeId = 10,
                            ScentId = 3
                        },
                        new
                        {
                            PerfumeId = 10,
                            ScentId = 4
                        },
                        new
                        {
                            PerfumeId = 11,
                            ScentId = 8
                        },
                        new
                        {
                            PerfumeId = 11,
                            ScentId = 9
                        },
                        new
                        {
                            PerfumeId = 12,
                            ScentId = 4
                        },
                        new
                        {
                            PerfumeId = 12,
                            ScentId = 15
                        },
                        new
                        {
                            PerfumeId = 13,
                            ScentId = 9
                        },
                        new
                        {
                            PerfumeId = 13,
                            ScentId = 2
                        },
                        new
                        {
                            PerfumeId = 14,
                            ScentId = 2
                        },
                        new
                        {
                            PerfumeId = 14,
                            ScentId = 8
                        },
                        new
                        {
                            PerfumeId = 15,
                            ScentId = 15
                        },
                        new
                        {
                            PerfumeId = 15,
                            ScentId = 3
                        },
                        new
                        {
                            PerfumeId = 16,
                            ScentId = 3
                        },
                        new
                        {
                            PerfumeId = 16,
                            ScentId = 4
                        },
                        new
                        {
                            PerfumeId = 17,
                            ScentId = 8
                        },
                        new
                        {
                            PerfumeId = 17,
                            ScentId = 2
                        },
                        new
                        {
                            PerfumeId = 18,
                            ScentId = 9
                        },
                        new
                        {
                            PerfumeId = 18,
                            ScentId = 15
                        });
                });

            modelBuilder.Entity("PerfumeTopScents", b =>
                {
                    b.Property<int>("PerfumeId")
                        .HasColumnType("int");

                    b.Property<int>("ScentId")
                        .HasColumnType("int");

                    b.HasKey("PerfumeId", "ScentId");

                    b.HasIndex("ScentId");

                    b.ToTable("PerfumeTopScents");

                    b.HasData(
                        new
                        {
                            PerfumeId = 1,
                            ScentId = 10
                        },
                        new
                        {
                            PerfumeId = 1,
                            ScentId = 7
                        },
                        new
                        {
                            PerfumeId = 1,
                            ScentId = 11
                        },
                        new
                        {
                            PerfumeId = 2,
                            ScentId = 2
                        },
                        new
                        {
                            PerfumeId = 2,
                            ScentId = 10
                        },
                        new
                        {
                            PerfumeId = 2,
                            ScentId = 14
                        },
                        new
                        {
                            PerfumeId = 3,
                            ScentId = 6
                        },
                        new
                        {
                            PerfumeId = 3,
                            ScentId = 14
                        },
                        new
                        {
                            PerfumeId = 3,
                            ScentId = 16
                        },
                        new
                        {
                            PerfumeId = 4,
                            ScentId = 10
                        },
                        new
                        {
                            PerfumeId = 4,
                            ScentId = 11
                        },
                        new
                        {
                            PerfumeId = 5,
                            ScentId = 7
                        },
                        new
                        {
                            PerfumeId = 5,
                            ScentId = 16
                        },
                        new
                        {
                            PerfumeId = 5,
                            ScentId = 14
                        },
                        new
                        {
                            PerfumeId = 6,
                            ScentId = 10
                        },
                        new
                        {
                            PerfumeId = 7,
                            ScentId = 14
                        },
                        new
                        {
                            PerfumeId = 7,
                            ScentId = 7
                        },
                        new
                        {
                            PerfumeId = 7,
                            ScentId = 6
                        },
                        new
                        {
                            PerfumeId = 8,
                            ScentId = 11
                        },
                        new
                        {
                            PerfumeId = 8,
                            ScentId = 10
                        },
                        new
                        {
                            PerfumeId = 8,
                            ScentId = 7
                        },
                        new
                        {
                            PerfumeId = 9,
                            ScentId = 6
                        },
                        new
                        {
                            PerfumeId = 10,
                            ScentId = 7
                        },
                        new
                        {
                            PerfumeId = 10,
                            ScentId = 16
                        },
                        new
                        {
                            PerfumeId = 11,
                            ScentId = 10
                        },
                        new
                        {
                            PerfumeId = 11,
                            ScentId = 6
                        },
                        new
                        {
                            PerfumeId = 11,
                            ScentId = 11
                        },
                        new
                        {
                            PerfumeId = 12,
                            ScentId = 11
                        },
                        new
                        {
                            PerfumeId = 12,
                            ScentId = 14
                        },
                        new
                        {
                            PerfumeId = 13,
                            ScentId = 14
                        },
                        new
                        {
                            PerfumeId = 13,
                            ScentId = 7
                        },
                        new
                        {
                            PerfumeId = 13,
                            ScentId = 10
                        },
                        new
                        {
                            PerfumeId = 14,
                            ScentId = 16
                        },
                        new
                        {
                            PerfumeId = 15,
                            ScentId = 10
                        },
                        new
                        {
                            PerfumeId = 15,
                            ScentId = 6
                        },
                        new
                        {
                            PerfumeId = 15,
                            ScentId = 7
                        },
                        new
                        {
                            PerfumeId = 15,
                            ScentId = 11
                        },
                        new
                        {
                            PerfumeId = 16,
                            ScentId = 11
                        },
                        new
                        {
                            PerfumeId = 17,
                            ScentId = 7
                        },
                        new
                        {
                            PerfumeId = 17,
                            ScentId = 14
                        },
                        new
                        {
                            PerfumeId = 18,
                            ScentId = 14
                        },
                        new
                        {
                            PerfumeId = 18,
                            ScentId = 6
                        });
                });

            modelBuilder.Entity("Aromo.Models.Catalogue", b =>
                {
                    b.HasOne("Aromo.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Aromo.Models.Perfume", b =>
                {
                    b.HasOne("Aromo.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aromo.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aromo.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Gender");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("CataloguePerfume", b =>
                {
                    b.HasOne("Aromo.Models.Catalogue", null)
                        .WithMany()
                        .HasForeignKey("CataloguesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aromo.Models.Perfume", null)
                        .WithMany()
                        .HasForeignKey("PerfumesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Aromo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Aromo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aromo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Aromo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PerfumeBaseScents", b =>
                {
                    b.HasOne("Aromo.Models.Perfume", null)
                        .WithMany()
                        .HasForeignKey("PerfumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aromo.Models.Scent", null)
                        .WithMany()
                        .HasForeignKey("ScentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PerfumeHeartScents", b =>
                {
                    b.HasOne("Aromo.Models.Perfume", null)
                        .WithMany()
                        .HasForeignKey("PerfumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aromo.Models.Scent", null)
                        .WithMany()
                        .HasForeignKey("ScentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PerfumeTopScents", b =>
                {
                    b.HasOne("Aromo.Models.Perfume", null)
                        .WithMany()
                        .HasForeignKey("PerfumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aromo.Models.Scent", null)
                        .WithMany()
                        .HasForeignKey("ScentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
